### ISSUE TITLE
[Wish] Manually resize playlist columns

### ISSUE THREAD

**Issue by laubblaeser** [olegantonyan/mpz#135]
It would be nice if we could manually resize the columns of the playlist to accommodate long song titles and artist names. Currently the width of the columns is resized automatically dependent on the width of the playlist itself.

**Comment by olegantonyan** [comment]
It is actually fixed percent width, not auto. You can change this in `global.yml` config file (on Linux `~/.config/mpz/global.yml`)
The default columns config is this:
```
columns_config:
  - align: left
    field: artist
    stretch: false
    width_percent: 28
  - align: left
    field: album
    stretch: false
    width_percent: 28
  - align: left
    field: title
    stretch: false
    width_percent: 28
  - align: right
    field: year
    stretch: false
    width_percent: 5
  - align: right
    field: length
    stretch: true
    width_percent: 0
```
i.e. artist, album and title consume 28% width each
You can play around with `width_percent` for specific fields or remove/add other columns

More on this readme https://github.com/olegantonyan/mpz#columns-config
